---
title: "Jan26_draft"
author: "Akhila"
date: "January 26, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)


library(tidyverse)
library(here)
library(rio)
library(dplyr)
library(synthpop)

```

```{r load-n-clean-data}

raw <- import(here("data", "ocaps_pilot_feb17_2020.sav")) %>% 
  characterize()


long <- raw %>% 
  pivot_longer(
    cols = c("Q3_1":"Q3_7", "Q3_8":"Q3_10"),
    names_to = "toss",
    values_to =  "stu_gender",
    values_drop_na = TRUE
  ) %>% 
  pivot_longer(
    cols = c("Q4_1":"Q4_19"),
    names_to = "toss1",
    values_to = "live_with",
    values_drop_na = TRUE
  ) %>% 
  pivot_longer(
    cols = c("Q16_1":"Q16_15","Q16_16"),
    names_to = "toss2",
    values_to = "ethnicity",
    values_drop_na = TRUE
  ) %>% 
  dplyr::select(c("V1", "Q1", "Q2",
           "stu_gender", "live_with", "ethnicity", 
           "Q6", 
           "Q9":"Q15",
           "Q17":"Q28",
           "Q46":"Q51B", 
           "Q52A", "Q52B", "Q52D",
           "Q53A", "Q53B", "Q53D",
           "Q54A", "Q54B", "Q54D",
           "Q55A", "Q56A", "Q57A",
           "Q58": "Q61",
           "Q106":"Q108",
           "Q162":"Q163_13",
           "SATOT":"PACFPERP"
  ))
  
View(long)

ods <- long %>%
  mutate(district = factor(Q1),
         district = dplyr::recode(district,
                                'Siuslaw High School' = "Siuslaw",
                                'McKenzie High School' = "McKenzie",
                                'South Eugene High School' = "4J",
                                'Oakridge High School' = "Oakridge",
                                'Willamette High School' = "Bethel",
                                'Early College & Career Options (ECCO)' = "4J"))
head(ods)

```

```{r synthpop}


my.seed <- 17914709
sds.default <- syn(ods, seed = my.seed)


```

