---
title: "Jan26_draft"
author: "Akhila"
date: "January 26, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)


library(tidyverse)
library(here)
library(rio)
library(dplyr)

```

```{r load-n-clean-data}

raw <- import(here("data", "feb17_an.csv")) 
View(raw)

long <- raw %>% 
  pivot_longer(
    cols = c("Q3_1":"Q3_7", "Q3_8":"Q3_10"),
    names_to = "toss",
    values_to =  "stu_gender",
    values_drop_na = TRUE
  ) %>% 
  pivot_longer(
    cols = c("Q4_1":"Q4_19"),
    names_to = "toss1",
    values_to = "live_with",
    values_drop_na = TRUE
  ) %>% 
  pivot_longer(
    cols = c("Q16_1":"Q16_15","Q16_16"),
    names_to = "toss2",
    values_to = "ethnicity",
    values_drop_na = TRUE
  ) %>% 
  dplyr::select(c("id", "Q1", "Q2",
           "stu_gender", "live_with", "ethnicity",
           "Q9":"Q15",
           "Q17":"Q28",
           "Q46":"Q51B", 
           "Q52A", "Q52B", "Q52D",
           "Q53A", "Q53B", "Q53D",
           "Q54A", "Q54B", "Q54D",
           "Q55A", "Q56A", "Q57A",
           "Q58": "Q61",
           "Q106":"Q108",
           "Q162":"Q163_13",
           "SATOT":"PACFPERP"
  ))
  
View(long)

ods <- long %>%
  mutate(district = factor(Q1),
         district = dplyr::recode(district,
                                'Siuslaw High School' = "Siuslaw",
                                'McKenzie High School' = "McKenzie",
                                'South Eugene High School' = "4J",
                                'Oakridge High School' = "Oakridge",
                                'Willamette High School' = "Bethel",
                                'Early College & Career Options (ECCO)' = "4J"),
         stu_gender = as.factor(stu_gender))
head(ods)

```

```{r distributions}

ggplot(raw, aes(PATOTR)) +
  geom_bar() 

ggplot(raw, aes(Q157)) +
  geom_bar() 

ggplot(ods, aes(PATOTR)) +
  geom_bar() +
  facet_wrap(~district)

# Suggestion: What does PATOTR mean? Rename to something that helps viewer understand the x-axis. (Sorry if I missed this info somewhere!)

```

#Rates of Abuse By Gender and District
```{r plot1}

ggplot(ods, aes(as.factor(stu_gender), PATOTR)) +
	geom_violin(aes(fill = stu_gender), size = 1) +
	coord_flip() +
	facet_wrap(~district) +
	labs(y = "Physical Abuse Scores",
	     x = "Gender",
	     title = "Distribution of Abuse Rates",
	     subtitle = "Results displayed by gender and school district") 

#same for sexual abuse
ggplot(ods, aes(as.factor(stu_gender), PATOTR)) +
	geom_violin(aes(fill = stu_gender), size = 1) +
	coord_flip() +
	facet_wrap(~district) +
	labs(y = "Physical Abuse Scores",
	     x = "Gender",
	     title = "Distribution of Abuse Rates",
	     subtitle = "Results displayed by gender and school district") 
	
	
#playing with geom_ribbon	
ggplot(ods, aes(district, PATOTR)) +
  geom_ribbon(aes(fill = stu_gender, 
                  color = stu_gender,
                  ymin = 0,
                  ymax = PATOTR), alpha = 0.8)

# Suggestion: Geom_violin - Nice way to display this info by gender and school district. Of course, you'll want to swap out the numbers for labels in the legend, and also you could reorder the legend to mirror the plots (e.g. the plots go 1 to 9 bottom to top, but the legend goes 1 to 9 top to bottom. Make them the same?). Also, I wonder about having too many categories on the legend... is there a way to simplify this without losing info?

```

#Neighborhood safety by District and ethnicity
```{r plot2}

#yikes --- definitely need to find a better viz for this...
ods %>%
ggplot(aes(district, as.factor(ethnicity))) +
    geom_tile(aes(fill = Q24))

# ods %>%
# ggplot(aes(district, as.factor(ethnicity))) +
#     geom_col() +
#   facet_wrap(~Q24)

# Suggestion: I like the idea of showing neighborhood safety by district and ethnicity! I'm thinking about other ways you could plot this... maybe have 5 distribution plots, one for each district. And, similar to your violin plot, a depiction of perceived level of safety for each ethnicity?
```

#Total Exposure to Violence by feelings of safety and school district
```{r}

# safe <- ods %>% 
#   filter(Q162 == "Yes") 
# 
# safe
# 
# View(safe)
# ods %>% 
#   pivot_longer(
#     cols = c("Q163_1":"Q163_13"),
#     names_to = "toss",
#     values_to =  "stu_gender",
#     values_drop_na = TRUE
#   )



ods %>% 
  filter(!is.na(Q162),
         Q162 == "No" |
           Q162 == "Yes") %>%
ggplot(aes(district, IPVTOT)) +
  geom_ribbon(aes(fill = Q162, 
                  color = Q162,
                  ymin = 0,
                  ymax = IPVTOT), alpha = 0.8)

ods %>% 
  filter(!is.na(Q162),
         Q162 == "No" |
           Q162 == "Yes") %>%  
ggplot(aes(district, PATOTR)) +
  geom_col(aes(fill = Q162), position = "dodge") 

```

